# Generated by Django 5.0.4 on 2024-05-04 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='https://media.istockphoto.com/id/1496481124/photo/black-luxury-silk-textile-material-background.webp?b=1&s=170667a&w=0&k=20&c=LuJSE3BzWIqXRssxn_0XcDHXoPCf0btDjVkBHgQiM3E=', upload_to='profile_pictures')),
                ('location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
